### ISSUE TITLE
kodi 17

### ISSUE THREAD

**Issue by ghost** [s0faking/plugin.video.puls4#3]
Hi, Kodi 17 is nearing its release and I get errors using this plugin (although I'm not sure if it is kods fault as it worked with previous releases of kodi 17):

`08:54:06 1700.478027 T:1460790176   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!                                                
                                            Error Type: <type 'exceptions.ValueError'>                                                                
                                            Error Contents: No JSON object could be decoded                                                           
                                            Traceback (most recent call last):                                                                        
                                              File "/storage/.kodi/addons/plugin.video.puls4/default.py", line 233, in <module>                             
                                                getJSONVideos(top_url)                                                                                           
                                              File "/storage/.kodi/addons/plugin.video.puls4/default.py", line 55, in getJSONVideos
                                                data = json.loads(html.get("content"))
                                              File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
                                              File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
                                              File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
                                            ValueError: No JSON object could be decoded
                                            -->End of Python script error report<--
08:54:06 1700.583618 T:1615852448   ERROR: GetDirectory - Error getting plugin://plugin.video.puls4/?banner=%2Fstorage%2F.kodi%2Faddons%2Fplugin.video.puls4%2Fresources%2Fmedia%2Flogos%2FDefault.png&link=&mode=getTopVideos&backdrop=http%3A%2F%2Fgoo.gl%2FXWnTc&title=Most+Popular`

**Comment by s0faking** [comment]
Hi @luchmhor ,

i fixed the issues. the puls4 api has changed. had to remove the "Top Videos" Section but besides that everything should work as usual. enjoy

pushed the update right now, so in case you don't want to wait for it just use the Git Version

cheers,
s0fa
